### ISSUE TITLE
two images not found

### ISSUE THREAD

**Issue by fzied** [tmichett/do280_demo#1]
hi,
on generating PDF, two images are missing:
```
asciidoctor-pdf  DO280_Demo_Guide.adoc 
asciidoctor: WARNING: image to embed not found or not readable: /home/fzied/Documents/Training/do280_demo/images/Chapter5-f7116.png
asciidoctor: WARNING: image to embed not found or not readable: /home/fzied/Documents/Training/do280_demo/images/Chapter5-7fd47.png
```

**Comment by fzied** [comment]
I copied the images from CH5/images to images and problem solved
`cp CH5/images/Chapter5-* images/`

**Comment by tmichett** [comment]
Sorry about that. I need to have them in both places for Github. So I've fixed it and it *should* build properly now.

Thanks for reporting this. I had it marked down, but forgot to fix.
